name: Vivado Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        
      - name: Install Vivado
        run: |
         curl https://www.xilinx.com/bin/public/openDownload?filename=Xilinx_Vivado_SDK_2021.2_1216_1_Lin64.bin -O vivado_installer.bin
          chmod +x vivado_installer.bin
          ./vivado_installer.bin --accept-xilinxEULA --noexec --target ./vivado_installer
          cd vivado_installer
          ./xsetup --agree XilinxEULA,3rdPartyEULA --batch Install --config install_config.txt
      
      - name: Add Vivado to PATH
        run: |
          echo 'export PATH="$PATH:/tools/Xilinx/Vivado/2019.2/bin"' >> $GITHUB_ENV
      
      - name: Run Tcl Script
        run: |
          vivado.bat -mode batch -source script.tcl mycpu.xpr
