name: Vivado Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        
      - name: Install Vivado
        run: |
# 下载Vivado安装程序包
curl -o Xilinx_Unified_2019.2_1106_2127_Win64.exe "https://www.xilinx.com/bin/public/openDownload?filename=Xilinx_Unified_2019.2_1106_2127_Win64.exe"

# 运行安装程序并同意协议
start /B Xilinx_Unified_2019.2_1106_2127_Win64.exe /quiet /noRestart ACCEPT_EULA=1
      
      - name: Add Vivado to PATH
        run: |
          echo 'export PATH="$PATH:/tools/Xilinx/Vivado/2019.2/bin"' >> $GITHUB_ENV
      
      - name: Run Tcl Script
        run: |
          vivado.bat -mode batch -source script.tcl mycpu.xpr
